apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: upsidedownsamoyeds-tls
spec:
  secretName: upsidedownsamoyeds
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: upsidedownsamoyeds.com
  dnsNames:
    - upsidedownsamoyeds.com
    - www.upsidedownsamoyeds.com